DOMAIN = "solis_logging"
DEFAULT_NAME = "Solis Data Power"
DEFAULT_TIMEOUT = 10
DEFAULT_RETRIES = 2
DEFAULT_INTERVAL = 60
DEFAULT_IP_ADDRESS = "192.168.1.20"
DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "admin"

